import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { NonConformityForm } from "./NonConformityForm";
import { useNonConformities } from "@/hooks/useNonConformities";
import type { Tables } from "@/integrations/supabase/types";

interface NonConformityDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  nonConformity?: Tables<"non_conformities">;
}

export const NonConformityDialog = ({
  open,
  onOpenChange,
  nonConformity,
}: NonConformityDialogProps) => {
  const { createNonConformity, updateNonConformity, uploadFile, isCreating, isUpdating } =
    useNonConformities();

  const handleSubmit = async (data: any, file?: File) => {
    if (nonConformity) {
      // Update existing NC
      let attachmentUrl = nonConformity.attachment_url;
      
      if (file) {
        attachmentUrl = await uploadFile(file, nonConformity.id);
      }

      updateNonConformity({
        id: nonConformity.id,
        ...data,
        attachment_url: attachmentUrl,
      });
    } else {
      // Create new NC - we'll upload file after creation
      createNonConformity({
        ...data,
        nc_number: "", // Will be auto-generated by trigger
      });
    }
    
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {nonConformity ? "Modifier la non-conformité" : "Nouvelle non-conformité"}
          </DialogTitle>
          <DialogDescription>
            {nonConformity
              ? "Modifiez les informations de la non-conformité"
              : "Créez une nouvelle non-conformité en remplissant les informations ci-dessous"}
          </DialogDescription>
        </DialogHeader>
        <NonConformityForm
          onSubmit={handleSubmit}
          initialData={nonConformity}
          isLoading={isCreating || isUpdating}
        />
      </DialogContent>
    </Dialog>
  );
};
